version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r app/requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest -v --tb=short
      - run:
          name: Run coverage
          command: |
            . venv/bin/activate
            pytest --cov=app app/test_app.py
      - run:
          name: Finished pipeline
          command: |
            echo "Finished pipeline"

workflows:
  version: 2
  test and coverage:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
      
