version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  test:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Execution verify
          command: echo "CircleCI is working"

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
                - dev
      
