version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo

jobs:
  test_coverage:
    executor: python-executor
    steps:
      - checkout

      # Restore cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "app/requirements.txt" }}
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r app/requirements.txt

      # Save cache
      - save_cache:
          paths:
            - ~/.cache/pip
            - venv
          key: v1-dependencies-{{ checksum "app/requirements.txt" }}

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            pytest -v --tb=short

      - run:
          name: Run coverage
          command: |
            . venv/bin/activate
            pytest --cov=app app/test_app.py
            
      - run:
          name: Finished pipeline
          command: |
            echo "Finished pipeline"

workflows:
  version: 2
  test and coverage:
    jobs:
      - test_coverage:
          filters:
            branches:
              only:
                - main
                - dev
      
