name: PR Checks

on:
  pull_request:
    branches:
      - dev

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    outputs:
      python-version: "3.7"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: dependencies-${{ runner.os }}-${{ hashFiles('app/requirements.txt') }}
          restore-keys: |
            dependencies-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install pylint pytest pytest-cov

      - name: Save venv
        uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('app/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-

  linting:
    name: Linting with Pylint
    runs-on: ubuntu-latest
    needs: install_dependencies
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore virtualenv
        uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('app/requirements.txt') }}

      - name: Run Pylint
        run: |
          source venv/bin/activate
          pylint --rcfile=app/.pylintrc app/app.py

  test_coverage:
    name: Run Tests with Coverage
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore virtualenv
        uses: actions/cache@v4
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ hashFiles('app/requirements.txt') }}

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest -v --tb=short

      - name: Run coverage
        run: |
          source venv/bin/activate
          mkdir -p coverage_reports
          pytest --cov=app --cov-report=xml:coverage_reports/coverage.xml app/test_app.py

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage_reports/